# Generated by Django 3.2.13 on 2023-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='upload',
            field=models.ImageField(default='uploads/xbFIHeh.png', upload_to='uploads/'),
        ),
    ]
